name: cluck_rush
description: "Cluck Rush: The Egg Dash - A fast-paced chicken adventure game"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # Flame Game Engine
  flame: ^1.34.0
  flame_audio: ^2.11.12

  # Local Storage
  hive_ce: ^2.16.0
  hive_ce_flutter: ^2.3.3

  # UI Icons
  cupertino_icons: ^1.0.8
  flame_tiled: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/

  fonts:
    - family: LilitaOne
      fonts:
        - asset: assets/font/Lilita_One/LilitaOne-Regular.ttf

    - family: Rubik
      fonts:
        - asset: assets/font/Rubik/Rubik-Regular.ttf
        - asset: assets/font/Rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/font/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/font/Rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/font/Rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/font/Rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Rubik/Rubik-Black.ttf
          weight: 900
        - asset: assets/font/Rubik/Rubik-Italic.ttf
          style: italic
        - asset: assets/font/Rubik/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/font/Rubik/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/font/Rubik/Rubik-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/font/Rubik/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/font/Rubik/Rubik-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/font/Rubik/Rubik-BlackItalic.ttf
          weight: 900
          style: italic